apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: web-app-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    # Якщо GKE Ingress використовує NEGs (за замовчуванням), 
    # health check йде напряму в Pod на порт 8080 (targetPort)
    port: 8080
