apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
  annotations:
    # Підключаємо BackendConfig для кастомного health check на /healthz
    # Без цієї анотації GCE Ingress ігнорує web-app-backendconfig!
    cloud.google.com/backend-config: '{"default": "web-app-backendconfig"}'
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-app-svc # Назва вашого сервісу
                port:
                 number: 80 # Порт, який слухає сервіс
